[tool.kedro]
package_name = "kedro_mlops_shopping_trends"
project_name = "kedro_mlops_shopping_trends"
kedro_init_version = "0.19.8"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/kedro_mlops_shopping_trends -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]

[tool.kedro_telemetry]
project_id = "6d7a553d01c34406b51991b8f072da97"
